USE ban;

DROP TABLE IF EXISTS author;

CREATE TABLE author(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	criado TIMESTAMP DEFAULT 0 NOT NULL,
	modificado TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
	ultimo VARCHAR(30) NOT NULL,
	primeiro VARCHAR(30) NOT NULL,
	meio VARCHAR(200)
);
